version: "3.5"

services:    

  decrypt:
    restart: "no"
    image: decrypt_dbvis:1.0
    build:
      context: .
    entrypoint: /home/decrypter/decrypt_dbvis.py /config
    volumes:
    - type: bind
       # Set the location of your DbVis config directory here
      source: ${HOME}/.dbvis
      target: /config
    tty: true
